/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Color {
  name: string;
  englishName: string;
  hex: string;
}

export const COLORS: Color[] = [
    // Grayscale
    { name: 'سیاه', englishName: 'Black', hex: '#000000' },
    { name: 'خاکستری مات', englishName: 'Dim Gray', hex: '#696969' },
    { name: 'خاکستری', englishName: 'Gray', hex: '#808080' },
    { name: 'خاکستری تیره', englishName: 'Dark Gray', hex: '#A9A9A9' },
    { name: 'نقره‌ای', englishName: 'Silver', hex: '#C0C0C0' },
    { name: 'خاکستری روشن', englishName: 'Light Gray', hex: '#D3D3D3' },
    { name: 'سفید دودی', englishName: 'White Smoke', hex: '#F5F5F5' },
    { name: 'سفید', englishName: 'White', hex: '#FFFFFF' },
    
    // Reds
    { name: 'خرمایی', englishName: 'Maroon', hex: '#800000' },
    { name: 'قرمز تیره', englishName: 'Dark Red', hex: '#8B0000' },
    { name: 'آجری', englishName: 'Firebrick', hex: '#B22222' },
    { name: 'زرشکی', englishName: 'Crimson', hex: '#DC143C' },
    { name: 'قرمز', englishName: 'Red', hex: '#FF0000' },
    { name: 'قرمز نارنجی', englishName: 'Orange Red', hex: '#FF4500' },
    { name: 'گوجه‌ای', englishName: 'Tomato', hex: '#FF6347' },
    { name: 'مرجانی', englishName: 'Coral', hex: '#FF7F50' },
    { name: 'قرمز هندی', englishName: 'Indian Red', hex: '#CD5C5C' },
    { name: 'مرجانی روشن', englishName: 'Light Coral', hex: '#F08080' },
    { name: 'سالمون تیره', englishName: 'Dark Salmon', hex: '#E9967A' },
    { name: 'ماهی سالمون', englishName: 'Salmon', hex: '#FA8072' },
    { name: 'سالمون روشن', englishName: 'Light Salmon', hex: '#FFA07A' },

    // Pinks
    { name: 'صورتی پررنگ', englishName: 'Deep Pink', hex: '#FF1493' },
    { name: 'صورتی جیغ', englishName: 'Hot Pink', hex: '#FF69B4' },
    { name: 'قرمز بنفش کم‌رنگ', englishName: 'Pale Violet Red', hex: '#DB7093' },
    { name: 'صورتی', englishName: 'Pink', hex: '#FFC0CB' },
    { name: 'صورتی روشن', englishName: 'Light Pink', hex: '#FFB6C1' },
    
    // Oranges
    { name: 'نارنجی تیره', englishName: 'Dark Orange', hex: '#FF8C00' },
    { name: 'نارنجی', englishName: 'Orange', hex: '#FFA500' },
    
    // Yellows
    { name: 'کهربایی', englishName: 'Amber', hex: '#FFBF00' },
    { name: 'طلایی', englishName: 'Gold', hex: '#FFD700' },
    { name: 'زرد', englishName: 'Yellow', hex: '#FFFF00' },
    { name: 'خاکی', englishName: 'Khaki', hex: '#F0E68C' },
    { name: 'زرد کم‌رنگ', englishName: 'Pale Goldenrod', hex: '#EEE8AA' },
    { name: 'موزی', englishName: 'Moccasin', hex: '#FFE4B5' },
    { name: 'زرد لیمویی روشن', englishName: 'Lemon Chiffon', hex: '#FFFACD' },

    // Greens
    { name: 'سبز تیره', englishName: 'Dark Green', hex: '#006400' },
    { name: 'سبز', englishName: 'Green', hex: '#008000' },
    { name: 'سبز جنگلی', englishName: 'Forest Green', hex: '#228B22' },
    { name: 'سبز دریایی', englishName: 'Sea Green', hex: '#2E8B57' },
    { name: 'سبز لیمویی', englishName: 'Lime Green', hex: '#32CD32' },
    { name: 'سبز دریایی متوسط', englishName: 'Medium Sea Green', hex: '#3CB371' },
    { name: 'سبز بهاری', englishName: 'Spring Green', hex: '#00FF7F' },
    { name: 'لیمویی', englishName: 'Lime', hex: '#00FF00' },
    { name: 'سبز چمنی', englishName: 'Lawn Green', hex: '#7CFC00' },
    { name: 'سبز چارتری', englishName: 'Chartreuse', hex: '#7FFF00' },
    { name: 'سبز-زرد', englishName: 'Green Yellow', hex: '#ADFF2F' },
    { name: 'سبز روشن', englishName: 'Light Green', hex: '#90EE90' },
    { name: 'سبز کم‌رنگ', englishName: 'Pale Green', hex: '#98FB98' },
    { name: 'سبز دریایی روشن', englishName: 'Light Sea Green', hex: '#20B2AA' },
    
    // Olives
    { name: 'سبز زیتونی تیره', englishName: 'Dark Olive Green', hex: '#556B2F' },
    { name: 'زیتونی نظامی', englishName: 'Olive Drab', hex: '#6B8E23' },
    { name: 'زیتونی', englishName: 'Olive', hex: '#808000' },
    { name: 'سبز دریایی تیره', englishName: 'Dark Sea Green', hex: '#8FBC8F' },

    // Cyans & Teals
    { name: 'خاکستری سنگی تیره', englishName: 'Dark Slate Gray', hex: '#2F4F4F' },
    { name: 'سبز دودی', englishName: 'Teal', hex: '#008080' },
    { name: 'فیروزه‌ای تیره', englishName: 'Dark Cyan', hex: '#008B8B' },
    { name: 'آبی ارتشی', englishName: 'Cadet Blue', hex: '#5F9EA0' },
    { name: 'فیروزه‌ای', englishName: 'Cyan', hex: '#00FFFF' },
    { name: 'آبی دریایی', englishName: 'Aqua', hex: '#00FFFF' },
    { name: 'آکوامارین', englishName: 'Aquamarine', hex: '#7FFFD4' },
    { name: 'فیروزه‌ای روشن', englishName: 'Turquoise', hex: '#40E0D0' },
    { name: 'آکوامارین متوسط', englishName: 'Medium Aquamarine', hex: '#66CDAA' },
    { name: 'فیروزه‌ای کم‌رنگ', englishName: 'Pale Turquoise', hex: '#AFEEEE' },
    
    // Blues
    { name: 'سرمه‌ای', englishName: 'Navy', hex: '#000080' },
    { name: 'آبی تیره', englishName: 'Dark Blue', hex: '#00008B' },
    { name: 'آبی متوسط', englishName: 'Medium Blue', hex: '#0000CD' },
    { name: 'آبی', englishName: 'Blue', hex: '#0000FF' },
    { name: 'آبی متالیک', englishName: 'Dodger Blue', hex: '#1E90FF' },
    { name: 'آبی درباری', englishName: 'Royal Blue', hex: '#4169E1' },
    { name: 'آبی فولادی', englishName: 'Steel Blue', hex: '#4682B4' },
    { name: 'گل گندمی', englishName: 'Cornflower Blue', hex: '#6495ED' },
    { name: 'آبی آسمانی', englishName: 'Sky Blue', hex: '#87CEEB' },
    { name: 'آبی روشن', englishName: 'Light Blue', hex: '#ADD8E6' },
    { name: 'آبی پودری', englishName: 'Powder Blue', hex: '#B0E0E6' },
    { name: 'آبی فولادی روشن', englishName: 'Light Steel Blue', hex: '#B0C4DE' },

    // Purples, Violets, Magentas
    { name: 'نیلی', englishName: 'Indigo', hex: '#4B0082' },
    { name: 'بنفش', englishName: 'Purple', hex: '#800080' },
    { name: 'سرخابی تیره', englishName: 'Dark Magenta', hex: '#8B008B' },
    { name: 'بنفش تیره', englishName: 'Dark Violet', hex: '#9400D3' },
    { name: 'ارکیده‌ای تیره', englishName: 'Dark Orchid', hex: '#9932CC' },
    { name: 'آبی بنفش', englishName: 'Blue Violet', hex: '#8A2BE2' },
    { name: 'ارکیده‌ای متوسط', englishName: 'Medium Orchid', hex: '#BA55D3' },
    { name: 'بنفش روشن', englishName: 'Violet', hex: '#EE82EE' },
    { name: 'سرخابی', englishName: 'Magenta', hex: '#FF00FF' },
    { name: 'سرخابی روشن', englishName: 'Fuchsia', hex: '#FF00FF' },
    { name: 'ارکیده‌ای', englishName: 'Orchid', hex: '#DA70D6' },
    { name: 'آلوچه‌ای', englishName: 'Plum', hex: '#DDA0DD' },
    { name: 'خارخاسک', englishName: 'Thistle', hex: '#D8BFD8' },
    { name: 'اسطوخودوسی', englishName: 'Lavender', hex: '#E6E6FA' },
    
    // Browns
    { name: 'قهوه‌ای روشن', englishName: 'Saddle Brown', hex: '#8B4513' },
    { name: 'آجری', englishName: 'Sienna', hex: '#A0522D' },
    { name: 'قهوه‌ای', englishName: 'Brown', hex: '#A52A2A' },
    { name: 'پرویی', englishName: 'Peru', hex: '#CD853F' },
    { name: 'شکلاتی', englishName: 'Chocolate', hex: '#D2691E' },
    { name: 'قهوه‌ای شنی', englishName: 'Sandy Brown', hex: '#F4A460' },
    { name: 'برنزه', englishName: 'Tan', hex: '#D2B48C' },
    { name: 'گندمی', englishName: 'Wheat', hex: '#F5DEB3' },
    
    // Whites
    { name: 'کرم نعنایی', englishName: 'Mint Cream', hex: '#F5FFFA' },
    { name: 'خاکستری سنگی روشن', englishName: 'Light Slate Gray', hex: '#778899' },
    { name: 'خاکستری سنگی', englishName: 'Slate Gray', hex: '#708090' },
    { name: 'عسلی', englishName: 'Honeydew', hex: '#F0FFF0' },
    { name: 'آبی آلیس', englishName: 'Alice Blue', hex: '#F0F8FF' },
    { name: 'سفید روح', englishName: 'Ghost White', hex: '#F8F8FF' },
    { name: 'برفی', englishName: 'Snow', hex: '#FFFAFA' },
    { name: 'عاجی', englishName: 'Ivory', hex: '#FFFFF0' },
    { name: 'صدف دریایی', englishName: 'Seashell', hex: '#FFF5EE' },
    { name: 'کتانی', englishName: 'Linen', hex: '#FAF0E6' },
    { name: 'توری کهنه', englishName: 'Old Lace', hex: '#FDF5E6' },
    { name: 'بژ', englishName: 'Beige', hex: '#F5F5DC' },

    // More Colors to reach 500
    { name: 'آبی نیمه‌شب', englishName: 'Midnight Blue', hex: '#191970' },
    { name: 'سبز زیتونی سیر', englishName: 'DarkSlateGray', hex: '#2F4F4F' },
    { name: 'نیلی سیر', englishName: 'SlateBlue', hex: '#6A5ACD' },
    { name: 'آبی-خاکستری', englishName: 'SlateGray', hex: '#708090' },
    { name: 'نیلی متالیک', englishName: 'MediumSlateBlue', hex: '#7B68EE' },
    { name: 'بنفش کم‌رنگ', englishName: 'MediumPurple', hex: '#9370DB' },
    { name: 'ارغوانی', englishName: 'RebeccaPurple', hex: '#663399' },
    { name: 'بنفش نیلی', englishName: 'DarkSlateBlue', hex: '#483D8B' },
    { name: 'اسطوخودوسی سرخ', englishName: 'LavenderBlush', hex: '#FFF0F5' },
    { name: 'صورتی مه آلود', englishName: 'MistyRose', hex: '#FFE4E1' },
    { name: 'سفید عتیقه', englishName: 'AntiqueWhite', hex: '#FAEBD7' },
    { name: 'هلویی', englishName: 'PapayaWhip', hex: '#FFEFD5' },
    { name: 'سفید بادامی', englishName: 'BlanchedAlmond', hex: '#FFEBCD' },
    { name: 'بیسکویتی', englishName: 'Bisque', hex: '#FFE4C4' },
    { name: 'بادامی', englishName: 'NavajoWhite', hex: '#FFDEAD' },
    { name: 'چوبی', englishName: 'BurlyWood', hex: '#DEB887' },
    { name: 'صورتی-قهوه‌ای', englishName: 'RosyBrown', hex: '#BC8F8F' },
    { name: 'طلایی کم‌رنگ', englishName: 'Goldenrod', hex: '#DAA520' },
    { name: 'طلایی سیر', englishName: 'DarkGoldenrod', hex: '#B8860B' },
    { name: 'کاهی', englishName: 'Cornsilk', hex: '#FFF8DC' },
    { name: 'سبز بهاری متوسط', englishName: 'MediumSpringGreen', hex: '#00FA9A' },
    { name: 'سبزآبی', englishName: 'MediumTurquoise', hex: '#48D1CC' },
    { name: 'فیروزه‌ای سیر', englishName: 'DarkTurquoise', hex: '#00CED1' },
    { name: 'آبی آسمانی سیر', englishName: 'DeepSkyBlue', hex: '#00BFFF' },
    { name: 'آبی آسمانی روشن', englishName: 'LightSkyBlue', hex: '#87CEFA' },
    { name: 'ارکیده‌ای بنفش', englishName: 'MediumVioletRed', hex: '#C71585' },
    { name: 'اخرایی', englishName: 'Ochre', hex: '#CC7722' },
    { name: 'قهوه‌ای مایل به قرمز', englishName: 'SaddleBrown', hex: '#8B4513' },
    { name: 'قهوه‌ای سوخته', englishName: 'Burnt Sienna', hex: '#E97451' },
    { name: 'ماگما', englishName: 'Magma', hex: '#FF3300' },
    { name: 'قرمز یاقوتی', englishName: 'Ruby', hex: '#E0115F' },
    { name: 'سبز زمردی', englishName: 'Emerald', hex: '#50C878' },
    { name: 'آبی یاقوتی', englishName: 'Sapphire', hex: '#0F52BA' },
    { name: 'کهربایی سیر', englishName: 'Dark Amber', hex: '#7B3F00' },
    { name: 'فیروزه‌ای ایرانی', englishName: 'Persian Blue', hex: '#1C39BB' },
    { name: 'سبز ایرانی', englishName: 'Persian Green', hex: '#00A693' },
    { name: 'قرمز ایرانی', englishName: 'Persian Red', hex: '#CC3333' },
    { name: 'صورتی ایرانی', englishName: 'Persian Pink', hex: '#F77FBE' },
    { name: 'نارنجی ایرانی', englishName: 'Persian Orange', hex: '#D99058' },
    { name: 'نیلی ایرانی', englishName: 'Persian Indigo', hex: '#32127A' },
    { name: 'آلویی ایرانی', englishName: 'Persian Plum', hex: '#701C1C' },
    { name: 'قرمز رز ایرانی', englishName: 'Persian Rose', hex: '#FE28A2' },
    { name: 'سبز کله‌غازی', englishName: 'Teal Green', hex: '#00827F' },
    { name: 'سبز پسته‌ای', englishName: 'Pistachio', hex: '#93C572' },
    { name: 'سبز نعنایی', englishName: 'Mint Green', hex: '#98FF98' },
    { name: 'سبز ارتشی', englishName: 'Army Green', hex: '#4B5320' },
    { name: 'سبز خزه‌ای', englishName: 'Moss Green', hex: '#8A9A5B' },
    { name: 'سبز مریم‌گلی', englishName: 'Sage Green', hex: '#B2AC88' },
    { name: 'سبز مارچوبه‌ای', englishName: 'Asparagus', hex: '#87A96B' },
    { name: 'سبز سرخسی', englishName: 'Fern Green', hex: '#4F7942' },
    { name: 'سبز اسلامی', englishName: 'Islamic Green', hex: '#009000' },
    { name: 'سبز هندی', englishName: 'India Green', hex: '#138808' },
    { name: 'سبز شکارچی', englishName: 'Hunter Green', hex: '#355E3B' },
    { name: 'سبز کلمی', englishName: 'Kelly Green', hex: '#4CBB17' },
    { name: 'سبز لجنی', englishName: 'Slime Green', hex: '#BCE954' },
    { name: 'سبز برقی', englishName: 'Electric Lime', hex: '#CCFF00' },
    { name: 'زرد فرانسوی', englishName: 'French Lime', hex: '#D0C201' },
    { name: 'سبز آووکادو', englishName: 'Avocado', hex: '#568203' },
    { name: 'سبز کاهویی', englishName: 'Chartreuse (Web)', hex: '#7FFF00' },
    { name: 'سبز لیمویی فسفری', englishName: 'Harlequin', hex: '#3FFF00' },
    { name: 'سبز بهاری تیره', englishName: 'Dark Spring Green', hex: '#177245' },
    { name: 'سبز دریایی شبدری', englishName: 'Shamrock Green', hex: '#009E60' },
    { name: 'سبز کوهی', englishName: 'Mountain Meadow', hex: '#30BA8F' },
    { name: 'سبز جنگلی استوایی', englishName: 'Jungle Green', hex: '#29AB87' },
    { name: 'سبز دریایی کارائیب', englishName: 'Caribbean Green', hex: '#00CC99' },
    { name: 'سبز آبی روشن', englishName: 'Tropical Rain Forest', hex: '#00755E' },
    { name: 'سبز کاجی', englishName: 'Pine Green', hex: '#01796F' },
    { name: 'سبز تیره نیمه‌شب', englishName: 'Dark Midnight Green', hex: '#003366' },
    { name: 'سبز آبی اقیانوسی', englishName: 'Deep Sea Green', hex: '#095859' },
    { name: 'سبز آبی بطری', englishName: 'Bottle Green', hex: '#006A4E' },
    { name: 'سبز دریایی عمیق', englishName: 'Seafoam Green', hex: '#9FE2BF' },
    { name: 'سبز چای', englishName: 'Tea Green', hex: '#D0F0C0' },
    { name: 'سبز کرفس', englishName: 'Celadon', hex: '#ACE1AF' },
    { name: 'سبز خردلی', englishName: 'Verdigris', hex: '#43B3AE' },
    { name: 'سبز ویرidian', englishName: 'Viridian', hex: '#40826D' },
    { name: 'سبز طاووسی', englishName: 'Peacock Green', hex: '#005F69' },
    { name: 'آبی طاووسی', englishName: 'Peacock Blue', hex: '#00529B' },
    { name: 'آبی سرولی', englishName: 'Cerulean', hex: '#007BA7' },
    { name: 'آبی لاجوردی', englishName: 'Azure', hex: '#007FFF' },
    { name: 'آبی آسمانی روشن', englishName: 'Baby Blue', hex: '#89CFF0' },
    { name: 'آبی کارولینا', englishName: 'Carolina Blue', hex: '#4B9CD3' },
    { name: 'آبی کبالت', englishName: 'Cobalt Blue', hex: '#0047AB' },
    { name: 'آبی مصری', englishName: 'Egyptian Blue', hex: '#1034A6' },
    { name: 'آبی برقی', englishName: 'Electric Blue', hex: '#7DF9FF' },
    { name: 'آبی یخی', englishName: 'Ice Blue', hex: '#99FFFF' },
    { name: 'آبی بین‌المللی کلاین', englishName: 'International Klein Blue', hex: '#002FA7' },
    { name: 'آبی پروس', englishName: 'Prussian Blue', hex: '#003153' },
    { name: 'آبی اولترامارین', englishName: 'Ultramarine', hex: '#120A8F' },
    { name: 'آبی دانشگاهی', englishName: 'University Blue', hex: '#4285F4' },
    { name: 'بنفش', englishName: 'Violet (color wheel)', hex: '#7F00FF' },
    { name: 'بنفش برقی', englishName: 'Electric Violet', hex: '#8F00FF' },
    { name: 'بنفش وایولا', englishName: 'Viola', hex: '#A569BD' },
    { name: 'بنفش اسطوخودوسی', englishName: 'Lavender (floral)', hex: '#B57EDC' },
    { name: 'بنفش یاسی', englishName: 'Lilac', hex: '#C8A2C8' },
    { name: 'بنفش ارغوانی', englishName: 'Mauve', hex: '#E0B0FF' },
    { name: 'بنفش پادشاهی', englishName: 'Royal Purple', hex: '#7851A9' },
    { name: 'بنفش بیزانسی', englishName: 'Byzantium', hex: '#702963' },
    { name: 'بنفش صورتی', englishName: 'Pansy', hex: '#78184A' },
    { name: 'بنفش ارکیده‌ای', englishName: 'Orchid (Crayola)', hex: '#E29CD2' },
    { name: 'بنفش هلندی', englishName: 'Heliotrope', hex: '#DF73FF' },
    { name: 'بنفش فسفری', englishName: 'Phlox', hex: '#DF00FF' },
    { name: 'بنفش تیره گرافیکی', englishName: 'Purple (X11)', hex: '#A020F0' },
    { name: 'بنفش امیتیست', englishName: 'Amethyst', hex: '#9966CC' },
    { name: 'بنفش تایرین', englishName: 'Tyrian Purple', hex: '#66023C' },
    { name: 'بنفش امپراطوری', englishName: 'Imperial Purple', hex: '#66023C' },
    { name: 'بنفش مات', englishName: 'Muted Purple', hex: '#800080' },
    { name: 'صورتی باربی', englishName: 'Barbie Pink', hex: '#E0218A' },
    { name: 'صورتی آبنباتی', englishName: 'Bubblegum Pink', hex: '#FFC1CC' },
    { name: 'صورتی گیلاسی', englishName: 'Cherry Blossom Pink', hex: '#FFB7C5' },
    { name: 'صورتی پنبه‌ای', englishName: 'Cotton Candy', hex: '#FFBCD9' },
    { name: 'صورتی فلامینگو', englishName: 'Flamingo Pink', hex: '#FC8EAC' },
    { name: 'صورتی فرانسوی', englishName: 'French Rose', hex: '#F64A8A' },
    { name: 'صورتی هالیوودی', englishName: 'Hollywood Cerise', hex: '#F400A1' },
    { name: 'صورتی لاوندر', englishName: 'Lavender Pink', hex: '#FBAED2' },
    { name: 'صورتی کوهی', englishName: 'Mountbatten Pink', hex: '#997A8D' },
    { name: 'صورتی ایرانی', englishName: 'Persian Pink', hex: '#F77FBE' },
    { name: 'صورتی رز', englishName: 'Rose Pink', hex: '#FF66CC' },
    { name: 'صورتی شوک', englishName: 'Shocking Pink', hex: '#FC0FC0' },
    { name: 'صورتی فولادی', englishName: 'Steel Pink', hex: '#CC3366' },
    { name: 'قهوه‌ای بژ', englishName: 'Beaver', hex: '#9F8170' },
    { name: 'قهوه‌ای سوخته', englishName: 'Bistre', hex: '#3D2B1F' },
    { name: 'قهوه‌ای برنزی', englishName: 'Bronze', hex: '#CD7F32' },
    { name: 'قهوه‌ای شتری', englishName: 'Camel', hex: '#C19A6B' },
    { name: 'قهوه‌ای دارچینی', englishName: 'Cinnamon', hex: '#D2691E' },
    { name: 'قهوه‌ای مسی', englishName: 'Copper', hex: '#B87333' },
    { name: 'قهوه‌ای خاکی', englishName: 'Fallow', hex: '#C19A6B' },
    { name: 'قهوه‌ای گردویی', englishName: 'Walnut Brown', hex: '#5C3317' },
    { name: 'قهوه‌ای حنایی', englishName: 'Russet', hex: '#80461B' },
    { name: 'قهوه‌ای اخرایی', englishName: 'Ochre', hex: '#CC7722' },
    { name: 'قهوه‌ای زنگاری', englishName: 'Rust', hex: '#B7410E' },
    { name: 'قهوه‌ای ماهگونی', englishName: 'Mahogany', hex: '#C04000' },
    { name: 'قهوه‌ای بلوطی', englishName: 'Chestnut', hex: '#954535' },
    { name: 'قهوه‌ای تیره', englishName: 'Dark Brown', hex: '#654321' },
    { name: 'نارنجی کدو تنبل', englishName: 'Pumpkin', hex: '#FF7518' },
    { name: 'نارنجی زردآلو', englishName: 'Apricot', hex: '#FBCEB1' },
    { name: 'نارنجی هویج', englishName: 'Carrot', hex: '#ED9121' },
    { name: 'نارنجی هلویی', englishName: 'Peach', hex: '#FFE5B4' },
    { name: 'نارنجی زعفرانی', englishName: 'Saffron', hex: '#F4C430' },
    { name: 'نارنجی نارنگی', englishName: 'Tangerine', hex: '#F28500' },
    { name: 'نارنجی ورمیلیون', englishName: 'Vermilion', hex: '#E34234' },
    { name: 'زرد قناری', englishName: 'Canary Yellow', hex: '#FFEF00' },
    { name: 'زرد ذرت', englishName: 'Corn', hex: '#FBEC5D' },
    { name: 'زرد کرم', englishName: 'Cream', hex: '#FFFDD0' },
    { name: 'زرد طلایی', englishName: 'Golden Yellow', hex: '#FFDF00' },
    { name: 'زرد خردلی', englishName: 'Mustard', hex: '#FFDB58' },
    { name: 'زرد گلرنگ', englishName: 'Saffron', hex: '#F4C430' },
    { name: 'زرد تیتانیوم', englishName: 'Titanium Yellow', hex: '#EEE600' },
    { name: 'زرد ناپل', englishName: 'Naples Yellow', hex: '#FADA5E' },
    { name: 'سفید یخی', englishName: 'Isabelline', hex: '#F4F0EC' },
    { name: 'سفید گچی', englishName: 'Gainsboro', hex: '#DCDCDC' },
    { name: 'سفید دریایی', englishName: 'Floral White', hex: '#FFFAF0' },
    { name: 'سفید عسلی', englishName: 'Honey', hex: '#F0FFF0' },
    { name: 'سفید یاسی', englishName: 'Lavender (web)', hex: '#E6E6FA' },
    { name: 'سفید مگنولیا', englishName: 'Magnolia', hex: '#F8F4FF' },
    { name: 'سفید پاپیونی', englishName: 'Papaya', hex: '#FFEFD5' },
    { name: 'سفید صدفی', englishName: 'Pearl', hex: '#EAE0C8' },
    { name: 'سفید پلاتینیوم', englishName: 'Platinum', hex: '#E5E4E2' },
    { name: 'سفید کوارتز', englishName: 'Quartz', hex: '#51414F' },
    { name: 'سفید شبح', englishName: 'Smoky White', hex: '#F5F5F5' },
    { name: 'مشکی ذغالی', englishName: 'Charcoal', hex: '#36454F' },
    { name: 'مشکی آبنوس', englishName: 'Ebony', hex: '#555D50' },
    { name: 'مشکی جوهری', englishName: 'Jet', hex: '#343434' },
    { name: 'مشکی اونیکس', englishName: 'Onyx', hex: '#353839' },
    { name: 'خاکستری سربی', englishName: 'Gunmetal', hex: '#2C3539' },
    { name: 'خاکستری فیلی', englishName: 'Taupe', hex: '#483C32' },
    { name: 'خاکستری نیکل', englishName: 'Nickel', hex: '#727472' },
    { name: 'نقره‌ای رومی', englishName: 'Roman Silver', hex: '#838996' },
    { name: 'نقره‌ای سونیک', englishName: 'Sonic Silver', hex: '#757575' },
    { name: 'نقره‌ای تیره', englishName: 'Old Silver', hex: '#848482' },
    // Adding more unique colors
    { name: 'شرابی', englishName: 'Burgundy', hex: '#800020' },
    { name: 'لاجوردی', englishName: 'Lapis Lazuli', hex: '#26619C' },
    { name: 'یشمی', englishName: 'Jade', hex: '#00A86B' },
    { name: 'هلویی-صورتی', englishName: 'Peach Puff', hex: '#FFDAB9' },
    { name: 'صورتی-نارنجی', englishName: 'Atomic Tangerine', hex: '#FF9966' },
    { name: 'سرخ گلی', englishName: 'Rose', hex: '#FF007F' },
    { name: 'آبی بوندی', englishName: 'Bondi Blue', hex: '#0095B6' },
    { name: 'سبز کله اردکی', englishName: 'Teal Blue', hex: '#367588' },
    { name: 'بنفش آمیتیست', englishName: 'Amethyst', hex: '#9966CC' },
    { name: 'نارنجی سوخته', englishName: 'Burnt Orange', hex: '#CC5500' },
    { name: 'قرمز کاردینال', englishName: 'Cardinal', hex: '#C41E3A' },
    { name: 'آبی کلمبیا', englishName: 'Columbia Blue', hex: '#C4D8E2' },
    { name: 'صورتی میخکی', englishName: 'Carnation Pink', hex: '#FFA6C9' },
    { name: 'آبی دنیم', englishName: 'Denim', hex: '#1560BD' },
    { name: 'سبز فلورسنتی', englishName: 'Electric Green', hex: '#00FF00' },
    { name: 'زرشکی گارنت', englishName: 'Garnet', hex: '#733635' },
    { name: 'طلایی متالیک', englishName: 'Metallic Gold', hex: '#D4AF37' },
    { name: 'سبز میرتل', englishName: 'Myrtle Green', hex: '#317873' },
    { name: 'آبی نفتی', englishName: 'Petrol', hex: '#005f6a' },
    { name: 'صورتی پاستلی', englishName: 'Pastel Pink', hex: '#DEA5A4' },
    { name: 'آبی پودری', englishName: 'Powder Blue', hex: '#B0E0E6' },
    { name: 'قرمز رادیکال', englishName: 'Radical Red', hex: '#FF355E' },
    { name: 'خاکستری رز', englishName: 'Rose Quartz', hex: '#AA98A9' },
    { name: 'زرد اخرایی', englishName: 'Sienna', hex: '#882D17' },
    { name: 'آبی تیفانی', englishName: 'Tiffany Blue', hex: '#0ABAB5' },
    { name: 'زرد وانیلی', englishName: 'Vanilla', hex: '#F3E5AB' },
    { name: 'بنفش ویستریا', englishName: 'Wisteria', hex: '#C9A0DC' },
    { name: 'خرمایی زنگی', englishName: 'Zinnwaldite', hex: '#EBC2AF' },
    { name: 'سبزآبی زافیر', englishName: 'Zaffre', hex: '#0014A8' },
    { name: 'سبز آمازون', englishName: 'Amazon', hex: '#3B7A57' },
    { name: 'آبی آسمانی آرژانتین', englishName: 'Argentinian Blue', hex: '#6CB4EE' },
    { name: 'قرمز شفق قطبی', englishName: 'Aurora Red', hex: '#B93A32' },
    { name: 'زرد بامبو', englishName: 'Bamboo', hex: '#DAA520' },
    { name: 'آبی بلیچ', englishName: 'Bleach Blue', hex: '#4F97A3' },
    { name: 'سبز کلم بروکلی', englishName: 'Broccoli Green', hex: '#4B5320' },
    { name: 'آبی کاپری', englishName: 'Capri', hex: '#00BFFF' },
    { name: 'قرمز گیلاسی', englishName: 'Cherry', hex: '#DE3163' },
    { name: 'سبز کلروفیلم', englishName: 'Chlorophyll Green', hex: '#4AFF00' },
    { name: 'قهوه‌ای نارگیل', englishName: 'Coconut', hex: '#965A3E' },
    { name: 'صورتی مرجانی', englishName: 'Coral Pink', hex: '#F88379' },
    { name: 'آبی کورن‌فلاور', englishName: 'Cornflower', hex: '#9ACEEB' },
    { name: 'قرمز زرشکی', englishName: 'Crimson Glory', hex: '#BE0032' },
    { name: 'آبی دلفینیوم', englishName: 'Delphinium Blue', hex: '#5D89B3' },
    { name: 'قرمز اژدها', englishName: 'Dragon Red', hex: '#B22222' },
    { name: 'خاکستری عقابی', englishName: 'Eagle Gray', hex: '#504A4B' },
    { name: 'سبز زمردی تیره', englishName: 'Dark Emerald', hex: '#005B41' },
    { name: 'قرمز فالو', englishName: 'Falu Red', hex: '#801818' },
    { name: 'آبی فدرال', englishName: 'Federal Blue', hex: '#394867' },
    { name: 'سبز سرخسی تیره', englishName: 'Dark Fern', hex: '#004225' },
    { name: 'قرمز آتشین', englishName: 'Fiery Red', hex: '#FF3300' },
    { name: 'آبی یخچالی', englishName: 'Glacier Blue', hex: '#78B1BF' },
    { name: 'زرد گریپ‌فروت', englishName: 'Grapefruit', hex: '#FF7518' },
    { name: 'خاکستری هاربر', englishName: 'Harbor Gray', hex: '#46535E' },
    { name: 'بنفش هیبیسکوس', englishName: 'Hibiscus', hex: '#B43757' },
    { name: 'آبی یخی', englishName: 'Iceberg', hex: '#71A6D2' },
    { name: 'قرمز ژاپنی', englishName: 'Japanese Red', hex: '#D70040' },
    { name: 'سبز ژوئن', englishName: 'June Bud', hex: '#BDDA57' },
    { name: 'آبی کپلر', englishName: 'Kepler', hex: '#3E6990' },
    { name: 'سبز خزه لاپلند', englishName: 'Lapland Moss', hex: '#99995A' },
    { name: 'قرمز لوگان‌بری', englishName: 'Loganberry', hex: '#791A39' },
    { name: 'آبی مایا', englishName: 'Maya Blue', hex: '#73C2FB' },
    { name: 'سبز نیمه‌شب', englishName: 'Midnight Green', hex: '#004953' },
    { name: 'قرمز انار', englishName: 'Pomegranate', hex: '#F34723' },
    { name: 'آبی پودری تیره', englishName: 'Dark Powder Blue', hex: '#003399' },
    { name: 'قرمز رزبری', englishName: 'Raspberry', hex: '#E30B5D' },
    { name: 'آبی ربین', englishName: 'Robin Egg Blue', hex: '#00CCCC' },
    { name: 'قرمز روستیک', englishName: 'Rustic Red', hex: '#7B3320' },
    { name: 'زرد شن', englishName: 'Sand', hex: '#C2B280' },
    { name: 'قرمز اسکارلت', englishName: 'Scarlet', hex: '#FF2400' },
    { name: 'آبی دریای شمال', englishName: 'North Sea Blue', hex: '#004F69' },
    { name: 'قهوه‌ای سپیا', englishName: 'Sepia', hex: '#704214' },
    { name: 'قرمز شنگرف', englishName: 'Cinnabar', hex: '#E34234' },
    { name: 'آبی سنگی', englishName: 'Stone Blue', hex: '#586E9D' },
    { name: 'قرمز توت فرنگی', englishName: 'Strawberry', hex: '#FC5A8D' },
    { name: 'زرد آفتابگردان', englishName: 'Sunflower', hex: '#FFDA03' },
    { name: 'قرمز ترش', englishName: 'Tart Red', hex: '#FF4D4D' },
    { name: 'آبی تبت', englishName: 'Tibetan Blue', hex: '#00426A' },
    { name: 'قرمز ونیزی', englishName: 'Venetian Red', hex: '#C80815' },
    { name: 'سبز وینترگرین', englishName: 'Wintergreen', hex: '#56887D' },
    { name: 'آبی ییل', englishName: 'Yale Blue', hex: '#0F4D92' },
    { name: 'قرمز زینفاندل', englishName: 'Zinfandel', hex: '#8A2145' },
    { name: 'زرد کهربایی آفریقا', englishName: 'African Amber', hex: '#CF7B25' },
    { name: 'خاکستری بالتی', englishName: 'Baltic Gray', hex: '#D2D2D2' },
    { name: 'آبی کارائیب', englishName: 'Caribbean Blue', hex: '#1AC1DD' },
    { name: 'سبز داکوتای', englishName: 'Dakota Green', hex: '#4B5D52' },
    { name: 'سبز اورستی', englishName: 'Everest Green', hex: '#6C7E6E' },
    { name: 'آبی فیجی', englishName: 'Fiji Blue', hex: '#4D658D' },
    { name: 'سبز گالاپاگوس', englishName: 'Galapagos Green', hex: '#2A5D64' },
    { name: 'آبی هیمالیا', englishName: 'Himalayan Blue', hex: '#657B83' },
    { name: 'سبز ایبیزا', englishName: 'Ibiza Green', hex: '#1A7A72' },
    { name: 'آبی جامائیکا', englishName: 'Jamaican Blue', hex: '#2C7594' },
    { name: 'سبز کنیا', englishName: 'Kenyan Green', hex: '#006430' },
    { name: 'آبی لابرادور', englishName: 'Labrador Blue', hex: '#262F3D' },
    { name: 'قرمز ماداگاسکار', englishName: 'Madagascar Red', hex: '#8B0000' },
    { name: 'آبی مالدیو', englishName: 'Maldives Blue', hex: '#0077BE' },
    { name: 'آبی نپال', englishName: 'Nepal Blue', hex: '#3C7A89' },
    { name: 'سبز نیوزلند', englishName: 'New Zealand Green', hex: '#006442' },
    { name: 'آبی اوکیناوا', englishName: 'Okinawa Blue', hex: '#006381' },
    { name: 'قرمز پرو', englishName: 'Peruvian Red', hex: '#CD5C5C' },
    { name: 'آبی کوئینزلند', englishName: 'Queensland Blue', hex: '#006594' },
    { name: 'قرمز ریو', englishName: 'Rio Red', hex: '#D50032' },
    { name: 'سبز صحرا', englishName: 'Sahara Green', hex: '#A8A162' },
    { name: 'آبی تاهیتی', englishName: 'Tahitian Blue', hex: '#0E5574' },
    { name: 'سبز اوگاندا', englishName: 'Ugandan Green', hex: '#005F41' },
    { name: 'قرمز وایکینگ', englishName: 'Viking Red', hex: '#9E1B32' },
    { name: 'آبی ویسکانسین', englishName: 'Wisconsin Blue', hex: '#0054A4' },
    { name: 'قرمز زنگبار', englishName: 'Zanzibar Red', hex: '#B22222' },
];