/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Country {
  name: string;
  capital: string;
  englishName: string;
  englishCapital: string;
}

export const COUNTRIES: Country[] = [
    { name: 'افغانستان', capital: 'کابل', englishName: 'Afghanistan', englishCapital: 'Kabul' },
    { name: 'آلبانی', capital: 'تیرانا', englishName: 'Albania', englishCapital: 'Tirana' },
    { name: 'الجزایر', capital: 'الجزیره', englishName: 'Algeria', englishCapital: 'Algiers' },
    { name: 'آندورا', capital: 'آندورا لا ولا', englishName: 'Andorra', englishCapital: 'Andorra la Vella' },
    { name: 'آنگولا', capital: 'لوآندا', englishName: 'Angola', englishCapital: 'Luanda' },
    { name: 'آنتیگوآ و باربودا', capital: 'سنت جانز', englishName: 'Antigua and Barbuda', englishCapital: 'Saint John\'s' },
    { name: 'آرژانتین', capital: 'بوئنوس آیرس', englishName: 'Argentina', englishCapital: 'Buenos Aires' },
    { name: 'ارمنستان', capital: 'ایروان', englishName: 'Armenia', englishCapital: 'Yerevan' },
    { name: 'استرالیا', capital: 'کانبرا', englishName: 'Australia', englishCapital: 'Canberra' },
    { name: 'اتریش', capital: 'وین', englishName: 'Austria', englishCapital: 'Vienna' },
    { name: 'آذربایجان', capital: 'باکو', englishName: 'Azerbaijan', englishCapital: 'Baku' },
    { name: 'باهاما', capital: 'ناسائو', englishName: 'Bahamas', englishCapital: 'Nassau' },
    { name: 'بحرین', capital: 'منامه', englishName: 'Bahrain', englishCapital: 'Manama' },
    { name: 'بنگلادش', capital: 'داکا', englishName: 'Bangladesh', englishCapital: 'Dhaka' },
    { name: 'باربادوس', capital: 'بریج‌تاون', englishName: 'Barbados', englishCapital: 'Bridgetown' },
    { name: 'بلاروس', capital: 'مینسک', englishName: 'Belarus', englishCapital: 'Minsk' },
    { name: 'بلژیک', capital: 'بروکسل', englishName: 'Belgium', englishCapital: 'Brussels' },
    { name: 'بلیز', capital: 'بلموپان', englishName: 'Belize', englishCapital: 'Belmopan' },
    { name: 'بنین', capital: 'پورتو نووو', englishName: 'Benin', englishCapital: 'Porto-Novo' },
    { name: 'بوتان', capital: 'تیمفو', englishName: 'Bhutan', englishCapital: 'Thimphu' },
    { name: 'بولیوی', capital: 'سوکره', englishName: 'Bolivia', englishCapital: 'Sucre' },
    { name: 'بوسنی و هرزگوین', capital: 'سارایوو', englishName: 'Bosnia and Herzegovina', englishCapital: 'Sarajevo' },
    { name: 'بوتسوانا', capital: 'گابورون', englishName: 'Botswana', englishCapital: 'Gaborone' },
    { name: 'برزیل', capital: 'برازیلیا', englishName: 'Brazil', englishCapital: 'Brasília' },
    { name: 'برونئی', capital: 'بندر سری بگاوان', englishName: 'Brunei', englishCapital: 'Bandar Seri Begawan' },
    { name: 'بلغارستان', capital: 'صوفیه', englishName: 'Bulgaria', englishCapital: 'Sofia' },
    { name: 'بورکینافاسو', capital: 'اوآگادوگو', englishName: 'Burkina Faso', englishCapital: 'Ouagadougou' },
    { name: 'بوروندی', capital: 'گیتگا', englishName: 'Burundi', englishCapital: 'Gitega' },
    { name: 'کامبوج', capital: 'پنوم‌پن', englishName: 'Cambodia', englishCapital: 'Phnom Penh' },
    { name: 'کامرون', capital: 'یائونده', englishName: 'Cameroon', englishCapital: 'Yaoundé' },
    { name: 'کانادا', capital: 'اتاوا', englishName: 'Canada', englishCapital: 'Ottawa' },
    { name: 'کیپ ورد', capital: 'پرایا', englishName: 'Cape Verde', englishCapital: 'Praia' },
    { name: 'جمهوری آفریقای مرکزی', capital: 'بانگی', englishName: 'Central African Republic', englishCapital: 'Bangui' },
    { name: 'چاد', capital: 'انجامنا', englishName: 'Chad', englishCapital: 'N\'Djamena' },
    { name: 'شیلی', capital: 'سانتیاگو', englishName: 'Chile', englishCapital: 'Santiago' },
    { name: 'چین', capital: 'پکن', englishName: 'China', englishCapital: 'Beijing' },
    { name: 'کلمبیا', capital: 'بوگوتا', englishName: 'Colombia', englishCapital: 'Bogotá' },
    { name: 'کومور', capital: 'مورونی', englishName: 'Comoros', englishCapital: 'Moroni' },
    { name: 'کاستاریکا', capital: 'سان خوزه', englishName: 'Costa Rica', englishCapital: 'San José' },
    { name: 'کرواسی', capital: 'زاگرب', englishName: 'Croatia', englishCapital: 'Zagreb' },
    { name: 'کوبا', capital: 'هاوانا', englishName: 'Cuba', englishCapital: 'Havana' },
    { name: 'قبرس', capital: 'نیکوزیا', englishName: 'Cyprus', englishCapital: 'Nicosia' },
    { name: 'جمهوری چک', capital: 'پراگ', englishName: 'Czech Republic', englishCapital: 'Prague' },
    { name: 'جمهوری دموکراتیک کنگو', capital: 'کینشاسا', englishName: 'Democratic Republic of the Congo', englishCapital: 'Kinshasa' },
    { name: 'دانمارک', capital: 'کپنهاگ', englishName: 'Denmark', englishCapital: 'Copenhagen' },
    { name: 'جیبوتی', capital: 'جیبوتی', englishName: 'Djibouti', englishCapital: 'Djibouti' },
    { name: 'دومینیکا', capital: 'روسو', englishName: 'Dominica', englishCapital: 'Roseau' },
    { name: 'جمهوری دومینیکن', capital: 'سانتو دومینگو', englishName: 'Dominican Republic', englishCapital: 'Santo Domingo' },
    { name: 'تیمور شرقی', capital: 'دیلی', englishName: 'East Timor', englishCapital: 'Dili' },
    { name: 'اکوادور', capital: 'کیتو', englishName: 'Ecuador', englishCapital: 'Quito' },
    { name: 'مصر', capital: 'قاهره', englishName: 'Egypt', englishCapital: 'Cairo' },
    { name: 'السالوادور', capital: 'سان سالوادور', englishName: 'El Salvador', englishCapital: 'San Salvador' },
    { name: 'گینه استوایی', capital: 'مالابو', englishName: 'Equatorial Guinea', englishCapital: 'Malabo' },
    { name: 'اریتره', capital: 'اسمره', englishName: 'Eritrea', englishCapital: 'Asmara' },
    { name: 'استونی', capital: 'تالین', englishName: 'Estonia', englishCapital: 'Tallinn' },
    { name: 'اسواتینی', capital: 'مبابانه', englishName: 'Eswatini', englishCapital: 'Mbabane' },
    { name: 'اتیوپی', capital: 'آدیس آبابا', englishName: 'Ethiopia', englishCapital: 'Addis Ababa' },
    { name: 'فیجی', capital: 'سووا', englishName: 'Fiji', englishCapital: 'Suva' },
    { name: 'فنلاند', capital: 'هلسینکی', englishName: 'Finland', englishCapital: 'Helsinki' },
    { name: 'فرانسه', capital: 'پاریس', englishName: 'France', englishCapital: 'Paris' },
    { name: 'گابن', capital: 'لیبرویل', englishName: 'Gabon', englishCapital: 'Libreville' },
    { name: 'گامبیا', capital: 'بانجول', englishName: 'Gambia', englishCapital: 'Banjul' },
    { name: 'گرجستان', capital: 'تفلیس', englishName: 'Georgia', englishCapital: 'Tbilisi' },
    { name: 'آلمان', capital: 'برلین', englishName: 'Germany', englishCapital: 'Berlin' },
    { name: 'غنا', capital: 'آکرا', englishName: 'Ghana', englishCapital: 'Accra' },
    { name: 'یونان', capital: 'آتن', englishName: 'Greece', englishCapital: 'Athens' },
    { name: 'گرنادا', capital: 'سنت جورجس', englishName: 'Grenada', englishCapital: 'St. George\'s' },
    { name: 'گواتمالا', capital: 'گواتمالاسیتی', englishName: 'Guatemala', englishCapital: 'Guatemala City' },
    { name: 'گینه', capital: 'کوناکری', englishName: 'Guinea', englishCapital: 'Conakry' },
    { name: 'گینه بیسائو', capital: 'بیسائو', englishName: 'Guinea-Bissau', englishCapital: 'Bissau' },
    { name: 'گویان', capital: 'جورج‌تاون', englishName: 'Guyana', englishCapital: 'Georgetown' },
    { name: 'هائیتی', capital: 'پورتو پرنس', englishName: 'Haiti', englishCapital: 'Port-au-Prince' },
    { name: 'هندوراس', capital: 'تگوسیگالپا', englishName: 'Honduras', englishCapital: 'Tegucigalpa' },
    { name: 'مجارستان', capital: 'بوداپست', englishName: 'Hungary', englishCapital: 'Budapest' },
    { name: 'ایسلند', capital: 'ریکیاویک', englishName: 'Iceland', englishCapital: 'Reykjavík' },
    { name: 'هند', capital: 'دهلی نو', englishName: 'India', englishCapital: 'New Delhi' },
    { name: 'اندونزی', capital: 'جاکارتا', englishName: 'Indonesia', englishCapital: 'Jakarta' },
    { name: 'ایران', capital: 'تهران', englishName: 'Iran', englishCapital: 'Tehran' },
    { name: 'عراق', capital: 'بغداد', englishName: 'Iraq', englishCapital: 'Baghdad' },
    { name: 'ایرلند', capital: 'دوبلین', englishName: 'Ireland', englishCapital: 'Dublin' },
    { name: 'اسرائیل', capital: 'اورشلیم', englishName: 'Israel', englishCapital: 'Jerusalem' },
    { name: 'ایتالیا', capital: 'رم', englishName: 'Italy', englishCapital: 'Rome' },
    { name: 'ساحل عاج', capital: 'یاموسوکرو', englishName: 'Ivory Coast', englishCapital: 'Yamoussoukro' },
    { name: 'جامائیکا', capital: 'کینگستون', englishName: 'Jamaica', englishCapital: 'Kingston' },
    { name: 'ژاپن', capital: 'توکیو', englishName: 'Japan', englishCapital: 'Tokyo' },
    { name: 'اردن', capital: 'امان', englishName: 'Jordan', englishCapital: 'Amman' },
    { name: 'قزاقستان', capital: 'آستانه', englishName: 'Kazakhstan', englishCapital: 'Astana' },
    { name: 'کنیا', capital: 'نایروبی', englishName: 'Kenya', englishCapital: 'Nairobi' },
    { name: 'کیریباتی', capital: 'تاراوای جنوبی', englishName: 'Kiribati', englishCapital: 'South Tarawa' },
    { name: 'کوزوو', capital: 'پریشتینا', englishName: 'Kosovo', englishCapital: 'Pristina' },
    { name: 'کویت', capital: 'کویت', englishName: 'Kuwait', englishCapital: 'Kuwait City' },
    { name: 'قرقیزستان', capital: 'بیشکک', englishName: 'Kyrgyzstan', englishCapital: 'Bishkek' },
    { name: 'لائوس', capital: 'وینتیان', englishName: 'Laos', englishCapital: 'Vientiane' },
    { name: 'لتونی', capital: 'ریگا', englishName: 'Latvia', englishCapital: 'Riga' },
    { name: 'لبنان', capital: 'بیروت', englishName: 'Lebanon', englishCapital: 'Beirut' },
    { name: 'لسوتو', capital: 'ماسرو', englishName: 'Lesotho', englishCapital: 'Maseru' },
    { name: 'لیبریا', capital: 'مونروویا', englishName: 'Liberia', englishCapital: 'Monrovia' },
    { name: 'لیبی', capital: 'طرابلس', englishName: 'Libya', englishCapital: 'Tripoli' },
    { name: 'لیختن‌اشتاین', capital: 'فادوتس', englishName: 'Liechtenstein', englishCapital: 'Vaduz' },
    { name: 'لیتوانی', capital: 'ویلنیوس', englishName: 'Lithuania', englishCapital: 'Vilnius' },
    { name: 'لوکزامبورگ', capital: 'لوکزامبورگ', englishName: 'Luxembourg', englishCapital: 'Luxembourg' },
    { name: 'ماداگاسکار', capital: 'آنتاناناریوو', englishName: 'Madagascar', englishCapital: 'Antananarivo' },
    { name: 'مالاوی', capital: 'لیلونگوه', englishName: 'Malawi', englishCapital: 'Lilongwe' },
    { name: 'مالزی', capital: 'کوالالومپور', englishName: 'Malaysia', englishCapital: 'Kuala Lumpur' },
    { name: 'مالدیو', capital: 'ماله', englishName: 'Maldives', englishCapital: 'Malé' },
    { name: 'مالی', capital: 'باماکو', englishName: 'Mali', englishCapital: 'Bamako' },
    { name: 'مالت', capital: 'والتا', englishName: 'Malta', englishCapital: 'Valletta' },
    { name: 'جزایر مارشال', capital: 'ماجورو', englishName: 'Marshall Islands', englishCapital: 'Majuro' },
    { name: 'موریتانی', capital: 'نواکشوت', englishName: 'Mauritania', englishCapital: 'Nouakchott' },
    { name: 'موریس', capital: 'پورت‌لوئیس', englishName: 'Mauritius', englishCapital: 'Port Louis' },
    { name: 'مکزیک', capital: 'مکزیکوسیتی', englishName: 'Mexico', englishCapital: 'Mexico City' },
    { name: 'میکرونزی', capital: 'پالیکیر', englishName: 'Micronesia', englishCapital: 'Palikir' },
    { name: 'مولداوی', capital: 'کیشیناو', englishName: 'Moldova', englishCapital: 'Chișinău' },
    { name: 'موناکو', capital: 'موناکو', englishName: 'Monaco', englishCapital: 'Monaco' },
    { name: 'مغولستان', capital: 'اولان‌باتور', englishName: 'Mongolia', englishCapital: 'Ulaanbaatar' },
    { name: 'مونته‌نگرو', capital: 'پودگوریتسا', englishName: 'Montenegro', englishCapital: 'Podgorica' },
    { name: 'مراکش', capital: 'رباط', englishName: 'Morocco', englishCapital: 'Rabat' },
    { name: 'موزامبیک', capital: 'ماپوتو', englishName: 'Mozambique', englishCapital: 'Maputo' },
    { name: 'میانمار', capital: 'نایپیداو', englishName: 'Myanmar', englishCapital: 'Naypyidaw' },
    { name: 'نامیبیا', capital: 'ویندهوک', englishName: 'Namibia', englishCapital: 'Windhoek' },
    { name: 'نائورو', capital: 'یارن', englishName: 'Nauru', englishCapital: 'Yaren' },
    { name: 'نپال', capital: 'کاتماندو', englishName: 'Nepal', englishCapital: 'Kathmandu' },
    { name: 'هلند', capital: 'آمستردام', englishName: 'Netherlands', englishCapital: 'Amsterdam' },
    { name: 'نیوزیلند', capital: 'ولینگتون', englishName: 'New Zealand', englishCapital: 'Wellington' },
    { name: 'نیکاراگوئه', capital: 'ماناگوآ', englishName: 'Nicaragua', englishCapital: 'Managua' },
    { name: 'نیجر', capital: 'نیامی', englishName: 'Niger', englishCapital: 'Niamey' },
    { name: 'نیجریه', capital: 'آبوجا', englishName: 'Nigeria', englishCapital: 'Abuja' },
    { name: 'کره شمالی', capital: 'پیونگ‌یانگ', englishName: 'North Korea', englishCapital: 'Pyongyang' },
    { name: 'مقدونیه شمالی', capital: 'اسکوپیه', englishName: 'North Macedonia', englishCapital: 'Skopje' },
    { name: 'نروژ', capital: 'اسلو', englishName: 'Norway', englishCapital: 'Oslo' },
    { name: 'عمان', capital: 'مسقط', englishName: 'Oman', englishCapital: 'Muscat' },
    { name: 'پاکستان', capital: 'اسلام‌آباد', englishName: 'Pakistan', englishCapital: 'Islamabad' },
    { name: 'پالائو', capital: 'نگرولمود', englishName: 'Palau', englishCapital: 'Ngerulmud' },
    { name: 'فلسطین', capital: 'اورشلیم شرقی', englishName: 'Palestine', englishCapital: 'East Jerusalem' },
    { name: 'پاناما', capital: 'پاناماسیتی', englishName: 'Panama', englishCapital: 'Panama City' },
    { name: 'پاپوآ گینه نو', capital: 'پورت مورسبی', englishName: 'Papua New Guinea', englishCapital: 'Port Moresby' },
    { name: 'پاراگوئه', capital: 'آسونسیون', englishName: 'Paraguay', englishCapital: 'Asunción' },
    { name: 'پرو', capital: 'لیما', englishName: 'Peru', englishCapital: 'Lima' },
    { name: 'فیلیپین', capital: 'مانیل', englishName: 'Philippines', englishCapital: 'Manila' },
    { name: 'لهستان', capital: 'ورشو', englishName: 'Poland', englishCapital: 'Warsaw' },
    { name: 'پرتغال', capital: 'لیسبون', englishName: 'Portugal', englishCapital: 'Lisbon' },
    { name: 'قطر', capital: 'دوحه', englishName: 'Qatar', englishCapital: 'Doha' },
    { name: 'جمهوری کنگو', capital: 'برازاویل', englishName: 'Republic of the Congo', englishCapital: 'Brazzaville' },
    { name: 'رومانی', capital: 'بخارست', englishName: 'Romania', englishCapital: 'Bucharest' },
    { name: 'روسیه', capital: 'مسکو', englishName: 'Russia', englishCapital: 'Moscow' },
    { name: 'روآندا', capital: 'کیگالی', englishName: 'Rwanda', englishCapital: 'Kigali' },
    { name: 'سنت کیتس و نویس', capital: 'باستر', englishName: 'Saint Kitts and Nevis', englishCapital: 'Basseterre' },
    { name: 'سنت لوسیا', capital: 'کاستریس', englishName: 'Saint Lucia', englishCapital: 'Castries' },
    { name: 'سنت وینسنت و گرنادین‌ها', capital: 'کینگزتاون', englishName: 'Saint Vincent and the Grenadines', englishCapital: 'Kingstown' },
    { name: 'ساموآ', capital: 'آپیا', englishName: 'Samoa', englishCapital: 'Apia' },
    { name: 'سان مارینو', capital: 'سان مارینو', englishName: 'San Marino', englishCapital: 'San Marino' },
    { name: 'سائوتومه و پرنسیپ', capital: 'سائوتومه', englishName: 'São Tomé and Príncipe', englishCapital: 'São Tomé' },
    { name: 'عربستان سعودی', capital: 'ریاض', englishName: 'Saudi Arabia', englishCapital: 'Riyadh' },
    { name: 'سنگال', capital: 'داکار', englishName: 'Senegal', englishCapital: 'Dakar' },
    { name: 'صربستان', capital: 'بلگراد', englishName: 'Serbia', englishCapital: 'Belgrade' },
    { name: 'سیشل', capital: 'ویکتوریا', englishName: 'Seychelles', englishCapital: 'Victoria' },
    { name: 'سیرالئون', capital: 'فری‌تاون', englishName: 'Sierra Leone', englishCapital: 'Freetown' },
    { name: 'سنگاپور', capital: 'سنگاپور', englishName: 'Singapore', englishCapital: 'Singapore' },
    { name: 'اسلواکی', capital: 'براتیسلاوا', englishName: 'Slovakia', englishCapital: 'Bratislava' },
    { name: 'اسلوونی', capital: 'لیوبلیانا', englishName: 'Slovenia', englishCapital: 'Ljubljana' },
    { name: 'جزایر سلیمان', capital: 'هونیارا', englishName: 'Solomon Islands', englishCapital: 'Honiara' },
    { name: 'سومالی', capital: 'موگادیشو', englishName: 'Somalia', englishCapital: 'Mogadishu' },
    { name: 'آفریقای جنوبی', capital: 'پرتوریا', englishName: 'South Africa', englishCapital: 'Pretoria' },
    { name: 'کره جنوبی', capital: 'سئول', englishName: 'South Korea', englishCapital: 'Seoul' },
    { name: 'سودان جنوبی', capital: 'جوبا', englishName: 'South Sudan', englishCapital: 'Juba' },
    { name: 'اسپانیا', capital: 'مادرید', englishName: 'Spain', englishCapital: 'Madrid' },
    { name: 'سری‌لانکا', capital: 'سری جایاواردنپورا کوته', englishName: 'Sri Lanka', englishCapital: 'Sri Jayawardenepura Kotte' },
    { name: 'سودان', capital: 'خارطوم', englishName: 'Sudan', englishCapital: 'Khartoum' },
    { name: 'سورینام', capital: 'پاراماریبو', englishName: 'Suriname', englishCapital: 'Paramaribo' },
    { name: 'سوئد', capital: 'استکهلم', englishName: 'Sweden', englishCapital: 'Stockholm' },
    { name: 'سوئیس', capital: 'برن', englishName: 'Switzerland', englishCapital: 'Bern' },
    { name: 'سوریه', capital: 'دمشق', englishName: 'Syria', englishCapital: 'Damascus' },
    { name: 'تایوان', capital: 'تایپه', englishName: 'Taiwan', englishCapital: 'Taipei' },
    { name: 'تاجیکستان', capital: 'دوشنبه', englishName: 'Tajikistan', englishCapital: 'Dushanbe' },
    { name: 'تانزانیا', capital: 'دودوما', englishName: 'Tanzania', englishCapital: 'Dodoma' },
    { name: 'تایلند', capital: 'بانکوک', englishName: 'Thailand', englishCapital: 'Bangkok' },
    { name: 'توگو', capital: 'لومه', englishName: 'Togo', englishCapital: 'Lomé' },
    { name: 'تونگا', capital: 'نوکوآلوفا', englishName: 'Tonga', englishCapital: 'Nukuʻalofa' },
    { name: 'ترینیداد و توباگو', capital: 'پورت آو اسپین', englishName: 'Trinidad and Tobago', englishCapital: 'Port of Spain' },
    { name: 'تونس', capital: 'تونس', englishName: 'Tunisia', englishCapital: 'Tunis' },
    { name: 'ترکیه', capital: 'آنکارا', englishName: 'Turkey', englishCapital: 'Ankara' },
    { name: 'ترکمنستان', capital: 'عشق‌آباد', englishName: 'Turkmenistan', englishCapital: 'Ashgabat' },
    { name: 'تووالو', capital: 'فونافوتی', englishName: 'Tuvalu', englishCapital: 'Funafuti' },
    { name: 'اوگاندا', capital: 'کامپالا', englishName: 'Uganda', englishCapital: 'Kampala' },
    { name: 'اوکراین', capital: 'کی‌یف', englishName: 'Ukraine', englishCapital: 'Kyiv' },
    { name: 'امارات متحده عربی', capital: 'ابوظبی', englishName: 'United Arab Emirates', englishCapital: 'Abu Dhabi' },
    { name: 'بریتانیا', capital: 'لندن', englishName: 'United Kingdom', englishCapital: 'London' },
    { name: 'ایالات متحده آمریکا', capital: 'واشینگتن، دی.سی.', englishName: 'United States', englishCapital: 'Washington, D.C.' },
    { name: 'اروگوئه', capital: 'مونته‌ویدئو', englishName: 'Uruguay', englishCapital: 'Montevideo' },
    { name: 'ازبکستان', capital: 'تاشکند', englishName: 'Uzbekistan', englishCapital: 'Tashkent' },
    { name: 'وانواتو', capital: 'پورت ویلا', englishName: 'Vanuatu', englishCapital: 'Port Vila' },
    { name: 'واتیکان', capital: 'واتیکان', englishName: 'Vatican City', englishCapital: 'Vatican City' },
    { name: 'ونزوئلا', capital: 'کاراکاس', englishName: 'Venezuela', englishCapital: 'Caracas' },
    { name: 'ویتنام', capital: 'هانوی', englishName: 'Vietnam', englishCapital: 'Hanoi' },
    { name: 'یمن', capital: 'صنعا', englishName: 'Yemen', englishCapital: 'Sana\'a' },
    { name: 'زامبیا', capital: 'لوساکا', englishName: 'Zambia', englishCapital: 'Lusaka' },
    { name: 'زیمبابوه', capital: 'هراره', englishName: 'Zimbabwe', englishCapital: 'Harare' },
];