/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface State {
  name: string;
  capital: string;
  englishName: string;
  englishCapital: string;
}

export const IRAN_STATES: State[] = [
    { name: 'آذربایجان شرقی', capital: 'تبریز', englishName: 'East Azerbaijan', englishCapital: 'Tabriz' },
    { name: 'آذربایجان غربی', capital: 'ارومیه', englishName: 'West Azerbaijan', englishCapital: 'Urmia' },
    { name: 'اردبیل', capital: 'اردبیل', englishName: 'Ardabil', englishCapital: 'Ardabil' },
    { name: 'اصفهان', capital: 'اصفهان', englishName: 'Isfahan', englishCapital: 'Isfahan' },
    { name: 'البرز', capital: 'کرج', englishName: 'Alborz', englishCapital: 'Karaj' },
    { name: 'ایلام', capital: 'ایلام', englishName: 'Ilam', englishCapital: 'Ilam' },
    { name: 'بوشهر', capital: 'بوشهر', englishName: 'Bushehr', englishCapital: 'Bushehr' },
    { name: 'تهران', capital: 'تهران', englishName: 'Tehran', englishCapital: 'Tehran' },
    { name: 'چهارمحال و بختیاری', capital: 'شهرکرد', englishName: 'Chaharmahal and Bakhtiari', englishCapital: 'Shahr-e Kord' },
    { name: 'خراسان جنوبی', capital: 'بیرجند', englishName: 'South Khorasan', englishCapital: 'Birjand' },
    { name: 'خراسان رضوی', capital: 'مشهد', englishName: 'Razavi Khorasan', englishCapital: 'Mashhad' },
    { name: 'خراسان شمالی', capital: 'بجنورد', englishName: 'North Khorasan', englishCapital: 'Bojnord' },
    { name: 'خوزستان', capital: 'اهواز', englishName: 'Khuzestan', englishCapital: 'Ahvaz' },
    { name: 'زنجان', capital: 'زنجان', englishName: 'Zanjan', englishCapital: 'Zanjan' },
    { name: 'سمنان', capital: 'سمنان', englishName: 'Semnan', englishCapital: 'Semnan' },
    { name: 'سیستان و بلوچستان', capital: 'زاهدان', englishName: 'Sistan and Baluchestan', englishCapital: 'Zahedan' },
    { name: 'فارس', capital: 'شیراز', englishName: 'Fars', englishCapital: 'Shiraz' },
    { name: 'قزوین', capital: 'قزوین', englishName: 'Qazvin', englishCapital: 'Qazvin' },
    { name: 'قم', capital: 'قم', englishName: 'Qom', englishCapital: 'Qom' },
    { name: 'کردستان', capital: 'سنندج', englishName: 'Kurdistan', englishCapital: 'Sanandaj' },
    { name: 'کرمان', capital: 'کرمان', englishName: 'Kerman', englishCapital: 'Kerman' },
    { name: 'کرمانشاه', capital: 'کرمانشاه', englishName: 'Kermanshah', englishCapital: 'Kermanshah' },
    { name: 'کهگیلویه و بویراحمد', capital: 'یاسوج', englishName: 'Kohgiluyeh and Boyer-Ahmad', englishCapital: 'Yasuj' },
    { name: 'گلستان', capital: 'گرگان', englishName: 'Golestan', englishCapital: 'Gorgan' },
    { name: 'گیلان', capital: 'رشت', englishName: 'Gilan', englishCapital: 'Rasht' },
    { name: 'لرستان', capital: 'خرم‌آباد', englishName: 'Lorestan', englishCapital: 'Khorramabad' },
    { name: 'مازندران', capital: 'ساری', englishName: 'Mazandaran', englishCapital: 'Sari' },
    { name: 'مرکزی', capital: 'اراک', englishName: 'Markazi', englishCapital: 'Arak' },
    { name: 'هرمزگان', capital: 'بندرعباس', englishName: 'Hormozgan', englishCapital: 'Bandar Abbas' },
    { name: 'همدان', capital: 'همدان', englishName: 'Hamadan', englishCapital: 'Hamadan' },
    { name: 'یزد', capital: 'یزد', englishName: 'Yazd', englishCapital: 'Yazd' },
];

export const USA_STATES: State[] = [
    { name: 'آلاباما', capital: 'مونتگمری', englishName: 'Alabama', englishCapital: 'Montgomery' },
    { name: 'آلاسکا', capital: 'جونو', englishName: 'Alaska', englishCapital: 'Juneau' },
    { name: 'آریزونا', capital: 'فینیکس', englishName: 'Arizona', englishCapital: 'Phoenix' },
    { name: 'آرکانزاس', capital: 'لیتل راک', englishName: 'Arkansas', englishCapital: 'Little Rock' },
    { name: 'کالیفرنیا', capital: 'ساکرامنتو', englishName: 'California', englishCapital: 'Sacramento' },
    { name: 'کلرادو', capital: 'دنور', englishName: 'Colorado', englishCapital: 'Denver' },
    { name: 'کنتیکت', capital: 'هارتفورد', englishName: 'Connecticut', englishCapital: 'Hartford' },
    { name: 'دلاور', capital: 'دوور', englishName: 'Delaware', englishCapital: 'Dover' },
    { name: 'فلوریدا', capital: 'تالاهاسی', englishName: 'Florida', englishCapital: 'Tallahassee' },
    { name: 'جورجیا', capital: 'آتلانتا', englishName: 'Georgia', englishCapital: 'Atlanta' },
    { name: 'هاوایی', capital: 'هونولولو', englishName: 'Hawaii', englishCapital: 'Honolulu' },
    { name: 'آیداهو', capital: 'بویزی', englishName: 'Idaho', englishCapital: 'Boise' },
    { name: 'ایلینوی', capital: 'اسپرینگ‌فیلد', englishName: 'Illinois', englishCapital: 'Springfield' },
    { name: 'ایندیانا', capital: 'ایندیاناپولیس', englishName: 'Indiana', englishCapital: 'Indianapolis' },
    { name: 'آیووا', capital: 'دی موین', englishName: 'Iowa', englishCapital: 'Des Moines' },
    { name: 'کانزاس', capital: 'توپیکا', englishName: 'Kansas', englishCapital: 'Topeka' },
    { name: 'کنتاکی', capital: 'فرانکفورت', englishName: 'Kentucky', englishCapital: 'Frankfort' },
    { name: 'لوئیزیانا', capital: 'باتون روژ', englishName: 'Louisiana', englishCapital: 'Baton Rouge' },
    { name: 'مین', capital: 'آگوستا', englishName: 'Maine', englishCapital: 'Augusta' },
    { name: 'مریلند', capital: 'آناپولیس', englishName: 'Maryland', englishCapital: 'Annapolis' },
    { name: 'ماساچوست', capital: 'بوستون', englishName: 'Massachusetts', englishCapital: 'Boston' },
    { name: 'میشیگان', capital: 'لنسینگ', englishName: 'Michigan', englishCapital: 'Lansing' },
    { name: 'مینه‌سوتا', capital: 'سینت پال', englishName: 'Minnesota', englishCapital: 'Saint Paul' },
    { name: 'میسیسیپی', capital: 'جکسون', englishName: 'Mississippi', englishCapital: 'Jackson' },
    { name: 'میزوری', capital: 'جفرسون‌سیتی', englishName: 'Missouri', englishCapital: 'Jefferson City' },
    { name: 'مونتانا', capital: 'هلنا', englishName: 'Montana', englishCapital: 'Helena' },
    { name: 'نبراسکا', capital: 'لینکلن', englishName: 'Nebraska', englishCapital: 'Lincoln' },
    { name: 'نوادا', capital: 'کارسون‌سیتی', englishName: 'Nevada', englishCapital: 'Carson City' },
    { name: 'نیوهمپشایر', capital: 'کنکورد', englishName: 'New Hampshire', englishCapital: 'Concord' },
    { name: 'نیوجرسی', capital: 'ترنتون', englishName: 'New Jersey', englishCapital: 'Trenton' },
    { name: 'نیومکزیکو', capital: 'سانتافه', englishName: 'New Mexico', englishCapital: 'Santa Fe' },
    { name: 'نیویورک', capital: 'آلبانی', englishName: 'New York', englishCapital: 'Albany' },
    { name: 'کارولینای شمالی', capital: 'رالی', englishName: 'North Carolina', englishCapital: 'Raleigh' },
    { name: 'داکوتای شمالی', capital: 'بیسمارک', englishName: 'North Dakota', englishCapital: 'Bismarck' },
    { name: 'اوهایو', capital: 'کلمبوس', englishName: 'Ohio', englishCapital: 'Columbus' },
    { name: 'اکلاهما', capital: 'اکلاهما سیتی', englishName: 'Oklahoma', englishCapital: 'Oklahoma City' },
    { name: 'اورگن', capital: 'سیلم', englishName: 'Oregon', englishCapital: 'Salem' },
    { name: 'پنسیلوانیا', capital: 'هریسبورگ', englishName: 'Pennsylvania', englishCapital: 'Harrisburg' },
    { name: 'رود آیلند', capital: 'پراویدنس', englishName: 'Rhode Island', englishCapital: 'Providence' },
    { name: 'کارولینای جنوبی', capital: 'کلمبیا', englishName: 'South Carolina', englishCapital: 'Columbia' },
    { name: 'داکوتای جنوبی', capital: 'پییر', englishName: 'South Dakota', englishCapital: 'Pierre' },
    { name: 'تنسی', capital: 'نشویل', englishName: 'Tennessee', englishCapital: 'Nashville' },
    { name: 'تگزاس', capital: 'آستین', englishName: 'Texas', englishCapital: 'Austin' },
    { name: 'یوتا', capital: 'سالت‌لیک‌سیتی', englishName: 'Utah', englishCapital: 'Salt Lake City' },
    { name: 'ورمانت', capital: 'مونپلیه', englishName: 'Vermont', englishCapital: 'Montpelier' },
    { name: 'ویرجینیا', capital: 'ریچموند', englishName: 'Virginia', englishCapital: 'Richmond' },
    { name: 'واشینگتن', capital: 'المپیا', englishName: 'Washington', englishCapital: 'Olympia' },
    { name: 'ویرجینیای غربی', capital: 'چارلستون', englishName: 'West Virginia', englishCapital: 'Charleston' },
    { name: 'ویسکانسین', capital: 'مدیسون', englishName: 'Wisconsin', englishCapital: 'Madison' },
    { name: 'وایومینگ', capital: 'شاین', englishName: 'Wyoming', englishCapital: 'Cheyenne' },
];
